language: go
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libopenal-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev libgl1-mesa-dev
go_import_path: engo.io/engo
go:
- 1.4
- 1.5
- 1.6
- tip
