version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\engo.io\engo

environment:
  GOPATH: c:\gopath
  GOROOT: C:\go-x86
  PATH: '%PATH%;C:\go-x86;C:\MinGW\bin'

install:
  - set PATH=%PATH:c:\go;=%
  - echo %GOPATH%
  - echo %PATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
